// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    ChartList: typeof import('./src/components/ChartList.vue')['default']
    ConfigDialog: typeof import('./src/components/ConfigDialog.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ContentDetail: typeof import('./src/components/ContentDetail.vue')['default']
    ContentList: typeof import('./src/components/ContentList.vue')['default']
    DraggableResizeableItem: typeof import('./src/components/DraggableResizeableItem.vue')['default']
    File: typeof import('./src/components/File.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PreviewItem: typeof import('./src/components/PreviewItem.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    TodoProcess: typeof import('./src/components/TodoProcess.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    ToolBarSwitcher: typeof import('./src/components/ToolBarSwitcher.vue')['default']
  }
}

export { }
