// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ADropdownButton: typeof import('@arco-design/web-vue')['DropdownButton']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    Calendar: typeof import('./src/component/Calendar.vue')['default']
    ChartList: typeof import('./src/component/ChartList.vue')['default']
    ConfigDialog: typeof import('./src/component/ConfigDialog.vue')['default']
    Content: typeof import('./src/component/Content.vue')['default']
    ContentDetail: typeof import('./src/component/ContentDetail.vue')['default']
    ContentList: typeof import('./src/component/ContentList.vue')['default']
    DatePicker: typeof import('./src/component/DatePicker.vue')['default']
    DraggableResizeableItem: typeof import('./src/component/DraggableResizeableItem.vue')['default']
    File: typeof import('./src/component/File.vue')['default']
    Index: typeof import('./src/component/Index.vue')['default']
    Menu: typeof import('./src/component/Menu.vue')['default']
    PreviewItem: typeof import('./src/component/PreviewItem.vue')['default']
    PriorityPicker: typeof import('./src/component/PriorityPicker.vue')['default']
    TodoItem: typeof import('./src/component/TodoItem.vue')['default']
    TodoList: typeof import('./src/component/TodoList.vue')['default']
    TodoProcess: typeof import('./src/component/TodoProcess.vue')['default']
    ToolBar: typeof import('./src/component/ToolBar.vue')['default']
    ToolBarSwitcher: typeof import('./src/component/ToolBarSwitcher.vue')['default']
  }
}

export { }
